<?php

namespace AppBundle\Repository;

/**
 * ingredienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ingredienteRepository extends \Doctrine\ORM\EntityRepository
{
}
