<?php

namespace AppBundle\Repository;

/**
 * PlatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatoRepository extends \Doctrine\ORM\EntityRepository
{
    //funcion que devuelve los platos para una pagina
    //con un numero de elemento
    public function paginaPlato($numPlato=3,$pagina=1)
    {
        $query = $this->createQueryBuilder('t')
             ->where('t.top = 1')
             ->setFirstResult($numPlato * ($pagina-1))
             ->setMaxResults($numPlato)
             ->getQuery();
             return $platos = $query->getResult();

    }
}
